package com.boyninja1555.icecore.lib.obu;

public enum OBUClientboundPackets {
    RESET(0),
    SET_STEP_HEIGHT(1),
    SET_DEFAULT_SLIPPERINESS(2),
    SET_BLOCKS_SLIPPERINESS(3),
    SET_BOAT_FALL_DAMAGE(4),
    SET_BOAT_WATER_ELEVATION(5),
    SET_AIR_CONTROL(6),
    SET_BOAT_JUMP_FORCE(7),
    SET_MODE(8),
    SET_GRAVITY(9),
    SET_YAW_ACCEL(10),
    SET_FORWARD_ACCEL(11),
    SET_BACKWARD_ACCEL(12),
    SET_TURN_ACCEL(13),
    ALLOW_ACCEL_STACKING(14),
    RESEND_VERSION(15),
    SET_UNDERWATER_CONTROL(16),
    SET_SURFACE_WATER_CONTROL(17),
    SET_EXCLUSIVE_MODE(18),
    SET_COYOTE_TIME(19),
    SET_WATER_JUMPING(20),
    SET_SWIM_FORCE(21),
    REMOVE_BLOCKS_SLIPPERINESS(22),
    CLEAR_SLIPPERINESS(23),
    MODE_SERIES(24),
    EXCLUSIVE_MODE_SERIES(25),
    SET_PER_BLOCK(26),
    SET_COLLISION_MODE(27),
    SET_STEP_WHILE_FALLING(28),
    SET_INTERPOLATION_COMPAT(29),
    SET_COLLISION_RESOLUTION(30),
    ADD_COLLISION_ENTITYTYPE_FILTER(31),
    CLEAR_COLLISION_ENTITYTYPE_FILTER(32);

    private final int value;

    OBUClientboundPackets(int value) {
        this.value = value;
    }

    public int value() {
        return value;
    }
}
